import type { Metadata } from "next";
import "./globals.css";
import { Comic_Relief } from "next/font/google";
import Navbar from "@/components/layout/Navbar";
import DashedFrame from "@/components/layout/DashedFrame";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Yizhe",
  description: "Generated by create next app",
};

const comicRelief = Comic_Relief({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-comic-relief",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${comicRelief.className} ${comicRelief.variable} antialiased`}
      >
        <div className="relative min-h-screen">
          <DashedFrame />
          <div className="fixed left-0 top-8 z-50 w-full">
            <Navbar />
          </div>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
